### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by zachysaur** [maszhongming/Multi-LoRA-Composition#3]
how can you add your own character and clothing lora

**Comment by maszhongming** [comment]
https://github.com/maszhongming/Multi-LoRA-Composition/blob/8321b9084d260ab927a42971d95afe1fcf7bf806/example.py#L40

You can modify the `lora_path` and `weight_name` during the initialization of LoRA to load your own LoRA weights.

**Comment by zachysaur** [comment]
this need to be from huggingface or you can  just directly upload lora file

**Comment by maszhongming** [comment]
Both are possible. LoRA can be sourced from Hugging Face or your local files.

**Comment by zachysaur** [comment]
so downloading and generating pictures only required creating envirement running requirements putting model in checking point and use it?

**Comment by maszhongming** [comment]
The workflow, as described in the README, is:

1. Select a specific stable diffusion model.
2. Initialize LoRAs, which can be loaded from Hugging Face or from your local files.
3. Choose the method you want to use ("merge", "switch", "composite").
4. Provide the text prompts for the images you want to generate.
5. Generate the images.

Overall, the input consists of several LoRAs and prompts, without downloading images.
