### ISSUE TITLE
[Explanation of evaluation] does not work and gpt4v will not ouput why.

### ISSUE THREAD

**Issue by YY-Wei** [maszhongming/Multi-LoRA-Composition#8]
It seems that Explanation of evaluation in [gpt4v.py](https://github.com/maszhongming/Multi-LoRA-Composition/blob/main/human_eval/gpt4v.py) cannot work, gpt4v will not output why.

**Comment by maszhongming** [comment]
[gpt4v.py](https://github.com/maszhongming/Multi-LoRA-Composition/blob/main/human_eval/gpt4v.py) takes 3 images generated by `Merge`, `Switch`, and `Composite` respectively as input. It then performs 4 comparative evaluations (`Merge` vs. `Switch`, `Switch` vs. `Merge`, `Merge` vs. `Composite`, and `Composite` vs. `Merge`) to calculate a score for each image.

For explanations of evaluation, you can refer to [evaluate.py](https://github.com/maszhongming/Multi-LoRA-Composition/blob/main/evaluate.py) and [eval.sh](https://github.com/maszhongming/Multi-LoRA-Composition/blob/main/eval.sh).
